package gr.dim.stas.model.module;

import gr.dim.stas.model.module.common.AppModule;
import gr.dim.stas.model.views.EmployeesViewImpl;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 06 00:09:44 EEST 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }


  /**
   * creates a new record in the Employees View Object.
   * Also executesEmptyRowSet in order not to fetch Data.
   */
  public void enterEmpsInInsertMode(){
   EmployeesViewImpl emps=(EmployeesViewImpl)this.getEmployeesView1();
   
   emps.executeEmptyRowSet(); // executeEmpty RowSet in order not to fetch Data.
   
   Row newRow=emps.createRow();
   
   emps.insertRow(newRow);
   
   emps.setCurrentRow(newRow);
      
  }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public ViewObjectImpl getEmployeesView1() {
        return (ViewObjectImpl)findViewObject("EmployeesView1");
    }

    /**
     * Container's getter for EmployeesView2.
     * @return EmployeesView2
     */
    public ViewObjectImpl getEmployeesView2() {
        return (ViewObjectImpl)findViewObject("EmployeesView2");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpManagerFkLink1");
    }
    
    
    
  
}
