package gr.dim.stas.model.entities;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 09 12:55:31 CEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsImpl extends EntityImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsImpl() {
    }

    /**
     * Validation method for Departments.
     */
    public boolean validateDepartments() {
        System.out.println("aeigamisou...");
        return true;
    }

    /**
     * @param departmentId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer departmentId) {
        return new Key(new Object[]{departmentId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("gr.dim.stas.model.entities.Departments");
    }


    /**
     * Validation method for DepartmentName.
     */
    public boolean validateDepartmentName(String departmentname) {
        
      System.out.println("this is a sample validation. no logic is added, it will always rollback in any case.");
       
        this.getDBTransaction().rollback();
        
        
        return true;
    }
}
