package gr.dim.stas.model.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 06 00:20:28 EEST 2010
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void enterEmpsInInsertMode();
}
