package gr.dim.stas.model.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 05 13:20:21 EEST 2010
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void enterEmpsInInsertMode();
}
