package gr.dim.stas.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 16 22:20:34 CEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountriesViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CountriesViewImpl() {
    }
}
