package model;

import oracle.jbo.Session;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 16 10:22:07 EEST 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public AppModuleImpl()
  {
  }

  /**
   * Container's getter for DepartmentsView1.
   * @return DepartmentsView1
   */
  public DepartmentsViewImpl getDepartmentsView1()
  {
    return (DepartmentsViewImpl)findViewObject("DepartmentsView1");
  }
  
  protected void prepareSession(Session session) {
    super.prepareSession(session);
//    getDBTransaction().setClearCacheOnRollback(false);
  }
}
