package gr.dim.stas.model.themodule.client;

import gr.dim.stas.model.themodule.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 28 22:38:51 EEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void findByKeyOnEmployees() {
        Object _ret =
            this.riInvokeExportedMethod(this,"findByKeyOnEmployees",null,null);
        return;
    }

    public void findByKeyOnEmployeeDetails() {
        Object _ret =
            this.riInvokeExportedMethod(this,"findByKeyOnEmployeeDetails",null,null);
        return;
    }
}
