package gr.dim.stas.model.appModule;

import gr.dim.stas.model.appModule.common.EmployeesModule;

import oracle.jbo.NameValuePairs;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 17 13:38:43 EET 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesModuleImpl extends ApplicationModuleImpl implements EmployeesModule {
  /**
   * This is the default constructor (do not remove).
   */
  public EmployeesModuleImpl() {
  }

  /**
   * Container's getter for EmployeesView1.
   * @return EmployeesView1
   */
  public ViewObjectImpl getEmployeesView1() {
    return (ViewObjectImpl)findViewObject("EmployeesView1");
  }
  
  /**
   * Creates
   * @param discriminatorValue
   */
  public void createEmployeesRow(String discriminatorValue){
       ViewObjectImpl empVo=this.getEmployeesView1();
       NameValuePairs nvp = new NameValuePairs();
       nvp.setAttribute("JobId",discriminatorValue);
       Row row=empVo.createAndInitRow(nvp);
       empVo.insertRow(row);
       empVo.setCurrentRow(row);
       
       

    
  }
}
