package gr.stas.dim.model.views.client;

import gr.stas.dim.model.views.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 08 12:04:25 EEST 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void createAndInitRowDepartment(Number empId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createAndInitRowDepartment",new String [] {"oracle.jbo.domain.Number"},new Object[] {empId});
        return;
    }

    public void createAndInitRowEmployees(Number depId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createAndInitRowEmployees",new String [] {"oracle.jbo.domain.Number"},new Object[] {depId});
        return;
    }

    public void createRowSetAttributeDepartment(Number empId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createRowSetAttributeDepartment",new String [] {"oracle.jbo.domain.Number"},new Object[] {empId});
        return;
    }

    public void createRowSetAttributeEmployees(Number depId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createRowSetAttributeEmployees",new String [] {"oracle.jbo.domain.Number"},new Object[] {depId});
        return;
    }

    public void createRowSetAttributeValuesDepartment(Number empId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createRowSetAttributeValuesDepartment",new String [] {"oracle.jbo.domain.Number"},new Object[] {empId});
        return;
    }

    public void createRowSetAttributeValuesEmployees(Number depId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createRowSetAttributeValuesEmployees",new String [] {"oracle.jbo.domain.Number"},new Object[] {depId});
        return;
    }
}
