package gr.dim.stas.model.themodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 28 22:38:51 EEST 2011
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void findByKeyOnEmployees();

    void findByKeyOnEmployeeDetails();
}
