package gr.dim.stas.model.module.client;

import gr.dim.stas.model.module.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 06 00:20:28 EEST 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void enterEmpsInInsertMode() {
        Object _ret =
            this.riInvokeExportedMethod(this,"enterEmpsInInsertMode",null,null);
        return;
    }
}
