package gr.stas.dim.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 30 15:02:21 EEST 2010
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    void changeQueryableProperty(String attrName, Boolean isQueryable);
}
