package gr.dim.stas.model.appmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 12 20:09:54 CEST 2012
// ---------------------------------------------------------------------
public interface HRModule extends ApplicationModule {
    void whatIsTheCurrentRow();
}
