package gr.dim.stas.model.module.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 10 00:47:35 EEST 2010
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void enterEmpsInInsertMode();
}
