package gr.dim.stas.model.appmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 16 15:53:02 CET 2011
// ---------------------------------------------------------------------
public interface HRModule extends ApplicationModule {
    String updateOtherRows(String value);
}
