package gr.dim.stas.model.appModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 17 13:47:16 EET 2010
// ---------------------------------------------------------------------
public interface EmployeesModule extends ApplicationModule {
  void createEmployeesRow(String discriminatorValue);
}
