package gr.dim.stas.model.appModule.client;

import gr.dim.stas.model.appModule.common.EmployeesModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 17 13:47:16 EET 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesModuleClient extends ApplicationModuleImpl implements EmployeesModule {
  /**
   * This is the default constructor (do not remove).
   */
  public EmployeesModuleClient() {
  }

  public void createEmployeesRow(String discriminatorValue) {
    Object _ret =
      this.riInvokeExportedMethod(this,"createEmployeesRow",new String [] {"java.lang.String"},new Object[] {discriminatorValue});
    return;
  }
}
