package gr.dim.stas.model.themodule;


import gr.dim.stas.model.themodule.common.AppModule;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 28 21:34:32 EEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    /**
     * calls the findByKey method of employeesView1 VO and sets the first row to  be the current Row.
     * @param key
     */
    public void findByKeyOnEmployees(){
      ViewObjectImpl empDetailsView1 = getEmpDetailsViewView1();
        Key  empDetKey = empDetailsView1.getCurrentRow().getKey();
        ViewObjectImpl employeesView1 = getEmployeesView1();
        Row[] byKey = employeesView1.findByKey(empDetKey, -1);
        if(byKey.length>0){
         Row firstRow= byKey[0];
         employeesView1.setCurrentRow(firstRow);
        }
    }
    
    /**
     * calls the findByKey method of empDetailViewView VO and sets the first row to be the current Row.
     * @param key
     */
    public void findByKeyOnEmployeeDetails(){
        Key empKey = getEmployeesView1().getCurrentRow().getKey();
        ViewObjectImpl empDetailsView1 = getEmpDetailsViewView1();
      Row[] byKey = empDetailsView1.findByKey(empKey, -1);
      if(byKey.length>0){
       Row firstRow= byKey[0];
       empDetailsView1.setCurrentRow(firstRow);
      }
    }

    /**
     * Container's getter for EmpDetailsViewView1.
     * @return EmpDetailsViewView1
     */
    public ViewObjectImpl getEmpDetailsViewView1() {
        return (ViewObjectImpl)findViewObject("EmpDetailsViewView1");
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public ViewObjectImpl getEmployeesView1() {
        return (ViewObjectImpl)findViewObject("EmployeesView1");
    }

    /**
     * Container's getter for EmployeesView2.
     * @return EmployeesView2
     */
    public ViewObjectImpl getEmployeesView2() {
        return (ViewObjectImpl)findViewObject("EmployeesView2");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpManagerFkLink1");
    }
}
