package gr.dim.stas.model.appmodule.client;

import gr.dim.stas.model.appmodule.common.HRModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 12 20:09:54 CEST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRModuleClient extends ApplicationModuleImpl implements HRModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRModuleClient() {
    }

    public void whatIsTheCurrentRow() {
        Object _ret =
            this.riInvokeExportedMethod(this,"whatIsTheCurrentRow",null,null);
        return;
    }
}
